import type { Metadata } from "next";
import "@/styles/globals.css";

import { Footer } from "@/components/layout/footer";

import { geist, ivyora } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html className={cn(ivyora.variable, geist.className)} lang="en">
			<body className={"antialiased"}>
				{children}

				<Footer />
			</body>
		</html>
	);
}
